export const APP_LOGIN_SUCCESS = 'APP_LOGIN_SUCCESS';

export const BIBLE_BOOKS_LIST_SUCCESS = 'BIBLE_BOOKS_LIST_SUCCESS';
export const BIBLE_BOOK_READ = 'BIBLE_BOOK_READ';

export const BIBLE_BOOKS_VERSES_LIST_SUCCESS =
  'BIBLE_BOOKS_VERSES_LIST_SUCCESS';
